#go.mod的module名字
mod_name: easygo

#协议相关的参数
proto:
  source: example/api/proto #协议源路径
  analysis: example/api/http #协议源解析后存放路径

#私有代码存放的参数
internal:
  entrance: example/internal/app/api #请求入口文件夹
  service: example/internal/app/service #业务代码文件夹
  route: example/internal/init/boot #路由启动存放文件，成功的路由会在这里统一启动，请在服务启动的时候调用InitRoute方法

#文档路径
doc:
  swagger: example/api/swagger #swagger存放路径
